# Generated by Django 2.2.28 on 2023-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_juan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csc', models.BigIntegerField()),
            ],
        ),
    ]
